services:
  uedp_udc:
    image: uedp-p:latest
    container_name: uedp_udc
    stdin_open: true
    tty: true
    user: "${MY_UID:-1000}:${MY_GID:-1000}"
    volumes:
      - .:/uedp-libs
    working_dir: /uedp-libs