import yaml, pprint
from .pydantic_model import *
from pydantic import BaseModel, field_validator, Field, ConfigDict

# DOC - Event in yaml.parse
'''
StreamStartEvent(encoding, start_mark, end_mark)
StreamEndEvent(start_mark, end_mark)
DocumentStartEvent(explicit, version, tags, start_mark, end_mark)
DocumentEndEvent(start_mark, end_mark)
SequenceStartEvent(anchor, tag, implicit, flow_style, start_mark, end_mark)
SequenceEndEvent(start_mark, end_mark)
MappingStartEvent(anchor, tag, implicit, flow_style, start_mark, end_mark)
MappingEndEvent(start_mark, end_mark)
AliasEvent(anchor, start_mark, end_mark)
ScalarEvent(anchor, tag, implicit, value, style, start_mark, end_mark)

The list above is the list of events that can be generated by the yaml parser. 
Each event has a start_mark and end_mark that indicate the position of the event in the input stream. 
'''

def _extract_anchor_map_for_indexed_group(yaml_text, group_name):
  anchor_map = {}
  current_index = None
  in_group = False

  for event in yaml.parse(yaml_text):
    if isinstance(event, yaml.ScalarEvent):
      if event.value == group_name:
        in_group = True
      elif in_group and event.value.isdigit():
        current_index = event.value
    elif isinstance(event, yaml.MappingStartEvent) and in_group and event.anchor:
      if current_index is not None:
        anchor_map[current_index] = event.anchor

  return anchor_map

def _extract_anchor_list_for_group(yaml_text, group_name):
  anchors = []
  in_group = False
  sequence_depth = None

  for event in yaml.parse(yaml_text):
    if isinstance(event, yaml.ScalarEvent) and event.value == group_name:
      in_group = True
      continue
    if in_group and isinstance(event, yaml.SequenceStartEvent):
      sequence_depth = 1
      continue
    if in_group and isinstance(event, yaml.SequenceEndEvent):
      in_group = False
      sequence_depth = None
      continue
    if in_group and sequence_depth == 1 and isinstance(event, yaml.MappingStartEvent):
      anchors.append(event.anchor or '')

  return anchors

def lukupmodel_tnorm_resrc(yaml_text):
  payload = yaml.safe_load(yaml_text) or {}
  entries = payload.get('tnorms', {})
  if not isinstance(entries, dict):
    return []

  # NOTE 
  '''
  Extract anchors when they are present in the source YAML. This mirrors the
  notes in the file: the object anchor is encountered right after the numeric
  index and before the nested resource blocks are mapped.
  '''
  anchor_map = {}
  current_index = None
  in_tnorms = False
  for event in yaml.parse(yaml_text):
    if isinstance(event, yaml.ScalarEvent):
      if event.value == 'tnorms':
        in_tnorms = True
      elif in_tnorms and event.value.isdigit():
        current_index = event.value
    elif isinstance(event, yaml.MappingStartEvent) and in_tnorms and event.anchor:
      if current_index is not None:
        anchor_map[current_index] = event.anchor

  out = []
  for index_key, item in entries.items():
    if not isinstance(item, dict):
      continue

    model = C_tnorm_resrc_obj.model_construct(
      index=str(index_key),
      handler=str(item.get('handler', '')),
      hex_val=str(item.get('hex_val', '')),
      id_symbol=str(item.get('id_symbol', '')),
      queue_name=str(item.get('queue_name', '')),
      anchor=anchor_map.get(str(index_key), ''),
      tsm_resrc=None,
      fsm_resrc=None,
    )

    tsm_resrc = item.get('tsm_resrc')
    if isinstance(tsm_resrc, dict):
      model.tsm_resrc = C_tnorm_tsm_resrc_obj(
        kwobject=str(tsm_resrc.get('object', '')),
        state_trans=list(tsm_resrc.get('state_trans', [])),
        states=list(tsm_resrc.get('states', [])),
        table=str(tsm_resrc.get('table', '')),
      )

    fsm_resrc = item.get('fsm_resrc')
    if isinstance(fsm_resrc, dict):
      model.fsm_resrc = C_tnorm_fsm_resrc_obj(
        kwobject=str(fsm_resrc.get('object', '')),
        states=list(fsm_resrc.get('states', [])),
      )

    out.append(model)

  return out

def lukupmodel_tpoll_resrc(yaml_text):
  payload = yaml.safe_load(yaml_text) or {}
  entries = payload.get('tpolls', {})
  if not isinstance(entries, dict):
    return []

  anchor_map = _extract_anchor_map_for_indexed_group(yaml_text, 'tpolls')
  out = []
  for index_key, item in entries.items():
    if not isinstance(item, dict):
      continue

    model = C_tpoll_resrc_obj.model_construct(
      index=str(index_key),
      hex_val=str(item.get('hex_val', '')),
      handler=str(item.get('handler', '')),
      id_symbol=str(item.get('id_symbol', '')),
      anchor=anchor_map.get(str(index_key), ''),
    )
    out.append(model)

  return out

def lukupmodel_sig_resrc(yaml_text):
  payload = yaml.safe_load(yaml_text) or {}
  entries = payload.get('sigs', {})
  if not isinstance(entries, dict):
    return []

  anchor_map = _extract_anchor_map_for_indexed_group(yaml_text, 'sigs')
  out = []
  for index_key, item in entries.items():
    if not isinstance(item, dict):
      continue

    model = C_sig_obj.model_construct(
      index=str(index_key),
      hex_val=str(item.get('hex_val', '')),
      id_symbol=str(item.get('id_symbol', '')),
    )
    model.anchor = anchor_map.get(str(index_key), '')
    out.append(model)

  return out

def _normalize_alias_value(value, prefer_key=None):
  if value is None:
    return None
  if isinstance(value, str):
    return value if value.upper() != 'NULL' else None
  if isinstance(value, (int, float, bool)):
    return str(value)
  if isinstance(value, dict):
    if prefer_key and prefer_key in value:
      return _normalize_alias_value(value.get(prefer_key))
    for key in ('id_symbol', 'name', 'object', 'hex_val', 'value'):
      if key in value:
        return _normalize_alias_value(value.get(key))
    return None
  return None

# DEPRECATED - _parse_data_value will be removed from section of actv-obj-post removal

def _parse_actv_obj(data):
  if not isinstance(data, dict):
    return None

  action = data.get('actv')
  code = None
  function = None
  args = []
  if isinstance(action, dict):
    action_kind = action.get('kind', action.get('type', 'c_call'))
    action = str(action_kind)
  if isinstance(data.get('actv'), dict):
    action_spec = data['actv']
    code = action_spec.get('code')
    function = action_spec.get('function', action_spec.get('call'))
    args = [str(arg) for arg in action_spec.get('args', [])]

  return C_act_obj(
    actv=str(action or ''),
    code=code or data.get('code'),
    function=function or data.get('function'),
    args=args or [str(arg) for arg in data.get('args', [])],
  )

def _parse_action_list(data):
  if data is None:
    return C_act_list_obj(steps=[])

  if isinstance(data, list):
    steps = [_parse_actv_obj(item) for item in data if _parse_actv_obj(item) is not None]
    return C_act_list_obj(steps=steps)

  if isinstance(data, dict):
    if 'steps' in data:
      steps = [_parse_actv_obj(item) for item in data.get('steps', []) if _parse_actv_obj(item) is not None]
      return C_act_list_obj(steps=steps)
    if 'actv' in data:
      item = _parse_actv_obj(data)
      return C_act_list_obj(steps=[item] if item else [])

  return C_act_list_obj(steps=[])

def _parse_trans_obj(data):
  if not isinstance(data, dict):
    return None
  return C_trans_obj(
    sig=_normalize_alias_value(data.get('sig'), 'id_symbol') or '',
    goto=_normalize_alias_value(data.get('goto')) or '',
  )

def _parse_tsm_obj(data):
  if not isinstance(data, dict):
    return None

  trans_raw = data.get('trans', [])
  trans_items = [_parse_trans_obj(item) for item in trans_raw if _parse_trans_obj(item) is not None]

  return C_tsm_obj(
    id=str(data.get('id', '')),
    trans=C_trans_list_obj(trans=trans_items),
    on_ntry=_parse_action_list(data.get('on_ntry')) if data.get('on_ntry') is not None else None,
    on_actv=_parse_action_list(data.get('on_actv')) if data.get('on_actv') is not None else None,
    on_exit=_parse_action_list(data.get('on_exit')) if data.get('on_exit') is not None else None,
  )

def _parse_onrecv_obj(data):
  if not isinstance(data, dict):
    return None

  steps = _parse_action_list(data.get('steps'))
  return C_onrecv_obj(
    sig=_normalize_alias_value(data.get('sig'), 'id_symbol') or '',
    goto=_normalize_alias_value(data.get('goto')) or '',
    steps=steps,
  )

def _parse_fsm_obj(data):
  if not isinstance(data, dict):
    return None

  recv_raw = data.get('on_recv', [])
  recv_items = [_parse_onrecv_obj(item) for item in recv_raw if _parse_onrecv_obj(item) is not None]
  return C_fsm_obj(
    id=str(data.get('id', '')),
    on_recv=C_onrecv_list_obj(on_recv=recv_items),
  )

def _parse_kwexec_obj(data):
  if not isinstance(data, dict):
    return None

  return C_kwexec_obj(
    on_sig=_normalize_alias_value(data.get('on_sig'), 'id_symbol') or '',
    steps=_parse_action_list(data.get('steps')),
  )

def _parse_trig_obj(data):
  if not isinstance(data, dict):
    return None

  post_urgent = data.get('post_urgent')
  return C_trig_obj(
    on_sig=_normalize_alias_value(data.get('on_sig'), 'id_symbol') or '',
    post_urgent=_parse_action_list(post_urgent) if post_urgent is not None else None,
  )

def _parse_escal_obj(data):
  if not isinstance(data, dict):
    return None

  trigger = data.get('trigger', [])
  return C_escal_obj(
    mode=str(data.get('mode', '')),
    trigger=C_trig_list_obj(trigger=[_parse_trig_obj(item) for item in trigger if _parse_trig_obj(item) is not None]),
  )

def lukupmodel_tnorm_logic(yaml_text):
  payload = yaml.safe_load(yaml_text) or {}
  tlist = payload.get('tlist', [])
  if not isinstance(tlist, list):
    return []

  out = []
  for item in tlist:
    if not isinstance(item, dict) or 'tnorm' not in item:
      continue

    task_name = str(item.get('tnorm', ''))
    model = C_tnorm_obj(task=task_name)

    if 'tsm' in item:
      tsm_raw = item.get('tsm', [])
      model.tsm = C_tsm_list_obj(
        tsm_list=[_parse_tsm_obj(x) for x in tsm_raw if _parse_tsm_obj(x) is not None]
      )

    if 'fsm' in item:
      fsm_raw = item.get('fsm', [])
      model.fsm = C_fsm_list_obj(
        fsm_list=[_parse_fsm_obj(x) for x in fsm_raw if _parse_fsm_obj(x) is not None]
      )

    if 'kwexec' in item:
      kwexec_raw = item.get('kwexec', [])
      model.kwexec = C_kwexec_list_obj(
        kwexec=[_parse_kwexec_obj(x) for x in kwexec_raw if _parse_kwexec_obj(x) is not None]
      )

    if 'escal' in item:
      model.escal = _parse_escal_obj(item.get('escal'))

    model.anchor = item.get('anchor') or None
    out.append(model)

  return out

def lukupmodel_tpoll_logic(yaml_text):
  """Parse the `tlist` entries with a `tpoll` task into C_tpoll_obj models."""
  payload = yaml.safe_load(yaml_text) or {}
  tlist = payload.get('tlist', [])
  if not isinstance(tlist, list):
    return []

  out = []
  for item in tlist:
    if not isinstance(item, dict) or 'tpoll' not in item:
      continue

    task_name = str(item.get('tpoll', ''))
    kwexec_raw = item.get('kwexec', [])
    if 'exec' in item:
      kwexec_raw = item.get('exec', [])

    parsed_kwexec = []
    if isinstance(kwexec_raw, list):
      for entry in kwexec_raw:
        if isinstance(entry, dict):
          parsed_kwexec.append(_parse_actv_obj(entry))
    elif isinstance(kwexec_raw, dict):
      action = _parse_actv_obj(kwexec_raw)
      if action:
        parsed_kwexec.append(action)

    out.append(C_tpoll_obj(tpoll=task_name, kwexec=[a for a in parsed_kwexec if a is not None]))

  return out

# DEPRECATED - Old TASK - Remove ISR support in syntax and generator.

def lukupmodel_outexec_logic(yaml_text):
  payload = yaml.safe_load(yaml_text) or {}
  entries = payload.get('outexec', [])
  if not isinstance(entries, list):
    return []

  out = []
  for item in entries:
    if not isinstance(item, dict):
      continue
    out.append(C_outexec_obj(
      name=str(item.get('name', '')),
      handler=str(item.get('handler', '')),
      context=_normalize_alias_value(item.get('context')),
      state=_normalize_alias_value(item.get('state')) or '',
    ))

  return out

def lukupmodel_glbda_logic(yaml_text):
  payload = yaml.safe_load(yaml_text) or {}
  entries = payload.get('glbda', [])
  if not isinstance(entries, list):
    entries = payload.get('glbda', {})
    if isinstance(entries, dict):
      items = []
      for index_key, item in entries.items():
        if isinstance(item, dict):
          item_with_index = dict(item)
          item_with_index['_index'] = str(index_key)
          items.append(item_with_index)
      entries = items
    else:
      return []

  anchors = _extract_anchor_list_for_group(yaml_text, 'glbda')
  out = []
  for idx, item in enumerate(entries, start=1):
    if not isinstance(item, dict):
      continue

    index_key = str(item.get('_index', idx))
    out.append(C_gda_resrc_obj(
      index=index_key,
      name=str(item.get('name', '')),
      kwtype=str(item.get('type', item.get('kwtype', ''))),
      initial_value=item.get('initial_value', ''),
      anchor=anchors[idx - 1] if idx - 1 < len(anchors) else '',
    ))

  return out

def lukupmodel_parse_sample(yaml_text):
  events = yaml.parse(yaml_text)
  pprint.pprint(list(events))
  print('--- End of Event Stream ---')

# STUB - Sample usage
if __name__ == '__main__':
  with open('sources/app/lstaxizer.yaml', 'r', encoding='utf-8') as f:
    yaml_sample = f.read()

  lukupmodel_parse_sample(yaml_sample)

  tnorm_items = lukupmodel_tnorm_resrc(yaml_sample)
  tpoll_items = lukupmodel_tpoll_resrc(yaml_sample)
  sig_items = lukupmodel_sig_resrc(yaml_sample)

  print('tnorm_count=', len(tnorm_items))
  for item in tnorm_items:
    print(item.index, item.id_symbol, item.handler, item.anchor)
    print('tsm =', item.tsm_resrc.kwobject if item.tsm_resrc else None)
    print('fsm =', item.fsm_resrc.kwobject if item.fsm_resrc else None)

  print('\n')

  print('tpoll_count=', len(tpoll_items))
  for item in tpoll_items:
    print(item.index, item.id_symbol, item.handler, item.anchor)

  print('\n')

  print('sig_count=', len(sig_items))
  for item in sig_items:
    print(item.index, item.id_symbol, item.hex_val, getattr(item, 'anchor', ''))

  print('\n')

  tnorm_logic_items = lukupmodel_tnorm_logic(yaml_sample)
  tpoll_logic_items = lukupmodel_tpoll_logic(yaml_sample)
  # DEPRECATED - Old TASK - Remove ISR support in syntax and generator.
  outexec_logic_items = lukupmodel_outexec_logic(yaml_sample)
  glbda_logic_items = lukupmodel_glbda_logic(yaml_sample)

  print('tnorm_logic_count=', len(tnorm_logic_items))
  print('\n')
  for item in tnorm_logic_items:
    print('task =', item.task)
    print('anchor =', item.anchor)
    if item.tsm:
      print('tsm_count =', len(item.tsm.tsm_list))
      for tsm in item.tsm.tsm_list:
        print('  state_id =', tsm.id)
        print('  trans =', [(t.sig, t.goto) for t in tsm.trans.trans])
        if tsm.on_ntry:
          print('  on_ntry =', [(a.actv, a.to, a.sig, a.data, a.ptype) for a in tsm.on_ntry.steps])
        if tsm.on_actv:
          print('  on_actv =', [(a.actv, a.to, a.sig, a.data, a.ptype) for a in tsm.on_actv.steps])
        if tsm.on_exit:
          print('  on_exit =', [(a.actv, a.to, a.sig, a.data, a.ptype) for a in tsm.on_exit.steps])
    if item.fsm:
      print('fsm_count =', len(item.fsm.fsm_list))
      for fsm in item.fsm.fsm_list:
        print('  fsm_id =', fsm.id)
        for recv in fsm.on_recv.on_recv:
          print('    recv_sig =', recv.sig, 'goto =', recv.goto)
          print('    recv_steps =', [(a.actv, a.to, a.sig, a.data, a.ptype) for a in recv.steps.steps])
    if item.kwexec:
      print('kwexec_count =', len(item.kwexec.kwexec))
      for kw in item.kwexec.kwexec:
        print('  kw_on_sig =', kw.on_sig)
        print('  kw_steps =', [(a.actv, a.to, a.sig, a.data, a.ptype) for a in kw.steps.steps])
    if item.escal:
      print('escal_mode =', item.escal.mode)
      print('escal_triggers =', [(t.on_sig, t.post_urgent.steps if t.post_urgent else None) for t in item.escal.trigger.trigger])
    print('\n')

  print('tpoll_logic_count=', len(tpoll_logic_items))
  for item in tpoll_logic_items:
    print('tpoll =', item.tpoll)
    print('kwexec_count =', len(item.kwexec))
    for act in item.kwexec:
      print('  action =', act.actv, act.to, act.sig, act.data, act.ptype)
    print('\n')

  # DEPRECATED - Old TASK - Remove ISR support in syntax and generator.

  print('outexec_logic_count=', len(outexec_logic_items))
  for item in outexec_logic_items:
    print('name =', item.name)
    print('handler =', item.handler)
    print('context =', item.context)
    print('state =', item.state)
    print('\n')

  print('glbda_logic_count=', len(glbda_logic_items))
  for item in glbda_logic_items:
    print('gda_index =', item.index)
    print('gda_name =', item.name)
    print('gda_type =', item.kwtype)
    print('gda_initial_value =', item.initial_value)
    print('\n')


# DEPRECATED - Old TASK
'''
1. Thực hiện phân tích cấu trúc trả về của event để phân tích chiến lược xử lý mapping vào model.
2. Xây dựng các chuỗi phân tách phụ thuộc sẵn có từ lstaxer.strucjec để hỗ trợ triển khai.

# STATUS - done
'''
