import yaml, pprint
from .pydantic_model import *
from pydantic import BaseModel, field_validator, Field, ConfigDict

# DOC - Event in yaml.parse
'''
StreamStartEvent(encoding, start_mark, end_mark)
StreamEndEvent(start_mark, end_mark)
DocumentStartEvent(explicit, version, tags, start_mark, end_mark)
DocumentEndEvent(start_mark, end_mark)
SequenceStartEvent(anchor, tag, implicit, flow_style, start_mark, end_mark)
SequenceEndEvent(start_mark, end_mark)
MappingStartEvent(anchor, tag, implicit, flow_style, start_mark, end_mark)
MappingEndEvent(start_mark, end_mark)
AliasEvent(anchor, start_mark, end_mark)
ScalarEvent(anchor, tag, implicit, value, style, start_mark, end_mark)

The list above is the list of events that can be generated by the yaml parser. 
Each event has a start_mark and end_mark that indicate the position of the event in the input stream. 
'''

# SECTION - Hierarchy Level Dependency Chain - hl-dpendjain

# NOTE
'''
Only `tnorm`, `tpoll`, `sig`, `glbda` is used with incremental index, the rest is used with string name.
Therefore, the idea is after the parser meet these keyword, it will meet the index of an object,
it must create a new instance of the model class, and then parse the rest of the object into the model class.

# STUB 
if (event = incremental index) and (event = tnorm or tpoll or sig or glbda):
  model.create()

Also, with the incremental index,
it must also mapping the next parsing level follow the specific attribute of the model class.
For example, in tnorm, the next parsing level must be mapping to `tsm_resrc` -> `fsm_resrc` -> `id_symbol` -> `queue_name` -> `handler` -> `hex_val`.
Therefore, if we encounter '1' in tnorm, the next parsing level must be mapping to `tsm_resrc` -> `fsm_resrc` -> `id_symbol` -> `queue_name` -> `handler` -> `hex_val`.
So, it should add a mapping to specify the next parsing level follow the specific attribute of the model class.
'''
level_1st_tag = ['tnorms', 'tpolls', 'sigs', 'glbda', 'tlist', 'isr', 'outexec']

level_2nd_tag_tnorms = ['tsm_resrc', 'fsm_resrc', 'id_symbol', 'queue_name', 'handler', 'hex_val']
level_2nd_tag_tpolls = ['id_symbol', 'handler', 'hex_val']
level_2nd_tag_sigs = ['id_symbol', 'hex_val']
level_2nd_tag_glbda = ['name', 'type', 'initial_value']
level_2nd_tag_tlist = ['tnorm', 'tpoll']
level_2nd_tag_isr = ['id', 'to', 'sig']
level_2nd_tag_outexec = ['name', 'handler', 'context', 'state']

level_3rd_tag_tsm_resrc = ['states', 'state_trans', 'object', 'table']
level_3rd_tag_fsm_resrc = ['states', 'object']
# NOTE - in tnorm and tpoll, the 3rd level tag is the intermadiate level tag, including `tsm`, `fsm` and `exec`

# NOTE - This dpendjain is the core chain of action - actv-obj
independent_level_actvobj_tag = ['actv', 'to', 'sig', 'data', 'ptype']

level_4th_tag_tnorm_tsm_item = ['id', 'trans', 'on_ntry', 'on_actv', 'on_exit']
level_4th_tag_tpoll_fsm_item = ['id', 'on_recv']
level_4th_tag_tlist_exec_item = independent_level_actvobj_tag
# NOTE - In special case of `exec`, the 4th level is the list of actv-obj, therefore, must be included

level_5th_tag_tsm_trans_obj = ['sig', 'goto']
# NOTE - In design, it could be single actv-obj or list of actv-obj, therefore, must be included
level_5th_tag_tsm_on_ntry_actv_exit_obj = ['steps', independent_level_actvobj_tag]

# !SECTION

# SECTION - Level Sequential Mapping 
lvel_seqmap = {
  # ANCHOR - tnorm mapping 
  'tnorms': level_2nd_tag_tnorms,
  'tsm_resrc': level_3rd_tag_tsm_resrc,
  'fsm_resrc': level_3rd_tag_fsm_resrc,

  # ANCHOR - tpoll mapping
  'tpolls': level_2nd_tag_tpolls,

  # ANCHOR - sig mapping
  'sigs': level_2nd_tag_sigs,

  # ANCHOR - glbda mapping
  'glbda': level_2nd_tag_glbda,

  # ANCHOR - tlist mapping
  'tlist': level_2nd_tag_tlist,
  'tsm': level_4th_tag_tnorm_tsm_item,
  'fsm': level_4th_tag_tpoll_fsm_item,
  'exec': level_4th_tag_tlist_exec_item,
  'on_ntry': level_5th_tag_tsm_on_ntry_actv_exit_obj,
  'on_actv': level_5th_tag_tsm_on_ntry_actv_exit_obj,
  'on_exit': level_5th_tag_tsm_on_ntry_actv_exit_obj,
  'trans': level_5th_tag_tsm_trans_obj,
  'steps': independent_level_actvobj_tag,

  # ANCHOR - isr mapping
  'isr': level_2nd_tag_isr,

  # ANCHOR - outexec mapping
  'outexec': level_2nd_tag_outexec,
}
# !SECTION

def _extract_anchor_map_for_indexed_group(yaml_text, group_name):
  """Collect anchor names for entries under an indexed YAML group like tnorms/tpolls/sigs."""
  anchor_map = {}
  current_index = None
  in_group = False

  for event in yaml.parse(yaml_text):
    if isinstance(event, yaml.ScalarEvent):
      if event.value == group_name:
        in_group = True
      elif in_group and event.value.isdigit():
        current_index = event.value
    elif isinstance(event, yaml.MappingStartEvent) and in_group and event.anchor:
      if current_index is not None:
        anchor_map[current_index] = event.anchor

  return anchor_map


def _extract_anchor_list_for_group(yaml_text, group_name):
  """Collect anchors attached to mapping items in a top-level YAML sequence."""
  anchors = []
  in_group = False
  sequence_depth = None

  for event in yaml.parse(yaml_text):
    if isinstance(event, yaml.ScalarEvent) and event.value == group_name:
      in_group = True
      continue
    if in_group and isinstance(event, yaml.SequenceStartEvent):
      sequence_depth = 1
      continue
    if in_group and isinstance(event, yaml.SequenceEndEvent):
      in_group = False
      sequence_depth = None
      continue
    if in_group and sequence_depth == 1 and isinstance(event, yaml.MappingStartEvent):
      anchors.append(event.anchor or '')

  return anchors


def lukupmodel_tnorm_resrc(yaml_text):
  """
  Parse the raw `tnorms` mapping from YAML and split each indexed entry into the
  resource model expected by `C_tnorm_resrc_obj`.

  The event stream design in the notes shows the dependency chain:
    tnorms -> index -> mapping anchor -> tsm_resrc -> ... -> fsm_resrc -> ...
  We keep this in mind by using the YAML document structure rather than a raw
  flat scalar parser, so the resulting model stays aligned with the schema in
  `pydantic_model.resrc.C_tnorm_resrc_obj`.
  """
  payload = yaml.safe_load(yaml_text) or {}
  entries = payload.get('tnorms', {})
  if not isinstance(entries, dict):
    return []

  # Extract anchors when they are present in the source YAML. This mirrors the
  # notes in the file: the object anchor is encountered right after the numeric
  # index and before the nested resource blocks are mapped.
  anchor_map = {}
  current_index = None
  in_tnorms = False
  for event in yaml.parse(yaml_text):
    if isinstance(event, yaml.ScalarEvent):
      if event.value == 'tnorms':
        in_tnorms = True
      elif in_tnorms and event.value.isdigit():
        current_index = event.value
    elif isinstance(event, yaml.MappingStartEvent) and in_tnorms and event.anchor:
      if current_index is not None:
        anchor_map[current_index] = event.anchor

  out = []
  for index_key, item in entries.items():
    if not isinstance(item, dict):
      continue

    model = C_tnorm_resrc_obj.model_construct(
      index=str(index_key),
      handler=str(item.get('handler', '')),
      hex_val=str(item.get('hex_val', '')),
      id_symbol=str(item.get('id_symbol', '')),
      queue_name=str(item.get('queue_name', '')),
      anchor=anchor_map.get(str(index_key), ''),
      tsm_resrc=None,
      fsm_resrc=None,
    )

    tsm_resrc = item.get('tsm_resrc')
    if isinstance(tsm_resrc, dict):
      model.tsm_resrc = C_tnorm_tsm_resrc_obj(
        kwobject=str(tsm_resrc.get('object', '')),
        state_trans=list(tsm_resrc.get('state_trans', [])),
        states=list(tsm_resrc.get('states', [])),
        table=str(tsm_resrc.get('table', '')),
      )

    fsm_resrc = item.get('fsm_resrc')
    if isinstance(fsm_resrc, dict):
      model.fsm_resrc = C_tnorm_fsm_resrc_obj(
        kwobject=str(fsm_resrc.get('object', '')),
        states=list(fsm_resrc.get('states', [])),
      )

    out.append(model)

  return out


def lukupmodel_tpoll_resrc(yaml_text):
  """Parse tpolls entries into C_tpoll_resrc_obj objects."""
  payload = yaml.safe_load(yaml_text) or {}
  entries = payload.get('tpolls', {})
  if not isinstance(entries, dict):
    return []

  anchor_map = _extract_anchor_map_for_indexed_group(yaml_text, 'tpolls')
  out = []
  for index_key, item in entries.items():
    if not isinstance(item, dict):
      continue

    model = C_tpoll_resrc_obj.model_construct(
      index=str(index_key),
      hex_val=str(item.get('hex_val', '')),
      handler=str(item.get('handler', '')),
      id_symbol=str(item.get('id_symbol', '')),
      anchor=anchor_map.get(str(index_key), ''),
    )
    out.append(model)

  return out


def lukupmodel_sig_resrc(yaml_text):
  """Parse sigs entries into C_sig_obj objects."""
  payload = yaml.safe_load(yaml_text) or {}
  entries = payload.get('sigs', {})
  if not isinstance(entries, dict):
    return []

  anchor_map = _extract_anchor_map_for_indexed_group(yaml_text, 'sigs')
  out = []
  for index_key, item in entries.items():
    if not isinstance(item, dict):
      continue

    model = C_sig_obj.model_construct(
      index=str(index_key),
      hex_val=str(item.get('hex_val', '')),
      id_symbol=str(item.get('id_symbol', '')),
    )
    model.anchor = anchor_map.get(str(index_key), '')
    out.append(model)

  return out


def _normalize_alias_value(value, prefer_key=None):
  if value is None:
    return None
  if isinstance(value, str):
    return value if value.upper() != 'NULL' else None
  if isinstance(value, (int, float, bool)):
    return str(value)
  if isinstance(value, dict):
    if prefer_key and prefer_key in value:
      return _normalize_alias_value(value.get(prefer_key))
    for key in ('id_symbol', 'name', 'object', 'hex_val', 'value'):
      if key in value:
        return _normalize_alias_value(value.get(key))
    return None
  return None


def _parse_data_value(value):
  if not isinstance(value, dict) or 'value' not in value:
    return _normalize_alias_value(value, 'name')

  return C_data_obj(
    value=_normalize_alias_value(value.get('value'), 'name') or '',
    type=_normalize_alias_value(value.get('type')),
    mode=_normalize_alias_value(value.get('mode')),
  )


def _parse_action_obj(data):
  if not isinstance(data, dict):
    return None

  action = data.get('actv')
  code = None
  function = None
  args = []
  if isinstance(action, dict):
    action_kind = action.get('kind', action.get('type', 'c_call'))
    action = str(action_kind)
  if isinstance(data.get('actv'), dict):
    action_spec = data['actv']
    code = action_spec.get('code')
    function = action_spec.get('function', action_spec.get('call'))
    args = [str(arg) for arg in action_spec.get('args', [])]

  return C_act_obj(
    actv=str(action or ''),
    to=_normalize_alias_value(data.get('to')),
    sig=_normalize_alias_value(data.get('sig'), 'id_symbol'),
    data=_parse_data_value(data.get('data')),
    ptype=_normalize_alias_value(data.get('ptype')),
    code=code or data.get('code'),
    function=function or data.get('function'),
    args=args or [str(arg) for arg in data.get('args', [])],
  )


def _parse_action_list(data):
  if data is None:
    return C_act_list_obj(steps=[])

  if isinstance(data, list):
    steps = [_parse_action_obj(item) for item in data if _parse_action_obj(item) is not None]
    return C_act_list_obj(steps=steps)

  if isinstance(data, dict):
    if 'steps' in data:
      steps = [_parse_action_obj(item) for item in data.get('steps', []) if _parse_action_obj(item) is not None]
      return C_act_list_obj(steps=steps)
    if 'actv' in data:
      item = _parse_action_obj(data)
      return C_act_list_obj(steps=[item] if item else [])

  return C_act_list_obj(steps=[])


def _parse_trans_obj(data):
  if not isinstance(data, dict):
    return None
  return C_trans_obj(
    sig=_normalize_alias_value(data.get('sig'), 'id_symbol') or '',
    goto=_normalize_alias_value(data.get('goto')) or '',
  )


def _parse_tsm_obj(data):
  if not isinstance(data, dict):
    return None

  trans_raw = data.get('trans', [])
  trans_items = [_parse_trans_obj(item) for item in trans_raw if _parse_trans_obj(item) is not None]

  return C_tsm_obj(
    id=str(data.get('id', '')),
    trans=C_trans_list_obj(trans=trans_items),
    on_ntry=_parse_action_list(data.get('on_ntry')) if data.get('on_ntry') is not None else None,
    on_actv=_parse_action_list(data.get('on_actv')) if data.get('on_actv') is not None else None,
    on_exit=_parse_action_list(data.get('on_exit')) if data.get('on_exit') is not None else None,
  )


def _parse_onrecv_obj(data):
  if not isinstance(data, dict):
    return None

  steps = _parse_action_list(data.get('steps'))
  return C_onrecv_obj(
    sig=_normalize_alias_value(data.get('sig'), 'id_symbol') or '',
    goto=_normalize_alias_value(data.get('goto')) or '',
    steps=steps,
  )


def _parse_fsm_obj(data):
  if not isinstance(data, dict):
    return None

  recv_raw = data.get('on_recv', [])
  recv_items = [_parse_onrecv_obj(item) for item in recv_raw if _parse_onrecv_obj(item) is not None]
  return C_fsm_obj(
    id=str(data.get('id', '')),
    on_recv=C_onrecv_list_obj(on_recv=recv_items),
  )


def _parse_kwexec_obj(data):
  if not isinstance(data, dict):
    return None

  return C_kwexec_obj(
    on_sig=_normalize_alias_value(data.get('on_sig'), 'id_symbol') or '',
    steps=_parse_action_list(data.get('steps')),
  )


def _parse_trig_obj(data):
  if not isinstance(data, dict):
    return None

  post_urgent = data.get('post_urgent')
  return C_trig_obj(
    on_sig=_normalize_alias_value(data.get('on_sig'), 'id_symbol') or '',
    post_urgent=_parse_action_list(post_urgent) if post_urgent is not None else None,
  )


def _parse_escal_obj(data):
  if not isinstance(data, dict):
    return None

  trigger = data.get('trigger', [])
  return C_escal_obj(
    mode=str(data.get('mode', '')),
    trigger=C_trig_list_obj(trigger=[_parse_trig_obj(item) for item in trigger if _parse_trig_obj(item) is not None]),
  )


def lukupmodel_tnorm_logic(yaml_text):
  """Parse the `tlist` entries with a `tnorm` task into C_tnorm_obj models."""
  payload = yaml.safe_load(yaml_text) or {}
  tlist = payload.get('tlist', [])
  if not isinstance(tlist, list):
    return []

  out = []
  for item in tlist:
    if not isinstance(item, dict) or 'tnorm' not in item:
      continue

    task_name = str(item.get('tnorm', ''))
    model = C_tnorm_obj(task=task_name)

    if 'tsm' in item:
      tsm_raw = item.get('tsm', [])
      model.tsm = C_tsm_list_obj(
        tsm_list=[_parse_tsm_obj(x) for x in tsm_raw if _parse_tsm_obj(x) is not None]
      )

    if 'fsm' in item:
      fsm_raw = item.get('fsm', [])
      model.fsm = C_fsm_list_obj(
        fsm_list=[_parse_fsm_obj(x) for x in fsm_raw if _parse_fsm_obj(x) is not None]
      )

    if 'kwexec' in item:
      kwexec_raw = item.get('kwexec', [])
      model.kwexec = C_kwexec_list_obj(
        kwexec=[_parse_kwexec_obj(x) for x in kwexec_raw if _parse_kwexec_obj(x) is not None]
      )

    if 'escal' in item:
      model.escal = _parse_escal_obj(item.get('escal'))

    model.anchor = item.get('anchor') or None
    out.append(model)

  return out


def lukupmodel_tpoll_logic(yaml_text):
  """Parse the `tlist` entries with a `tpoll` task into C_tpoll_obj models."""
  payload = yaml.safe_load(yaml_text) or {}
  tlist = payload.get('tlist', [])
  if not isinstance(tlist, list):
    return []

  out = []
  for item in tlist:
    if not isinstance(item, dict) or 'tpoll' not in item:
      continue

    task_name = str(item.get('tpoll', ''))
    kwexec_raw = item.get('kwexec', [])
    if 'exec' in item:
      kwexec_raw = item.get('exec', [])

    parsed_kwexec = []
    if isinstance(kwexec_raw, list):
      for entry in kwexec_raw:
        if isinstance(entry, dict):
          parsed_kwexec.append(_parse_action_obj(entry))
    elif isinstance(kwexec_raw, dict):
      action = _parse_action_obj(kwexec_raw)
      if action:
        parsed_kwexec.append(action)

    out.append(C_tpoll_obj(tpoll=task_name, kwexec=[a for a in parsed_kwexec if a is not None]))

  return out


def lukupmodel_isr_logic(yaml_text):
  """Parse top-level ISR entries into C_isr_obj models."""
  payload = yaml.safe_load(yaml_text) or {}
  entries = payload.get('isr', [])
  if not isinstance(entries, list):
    return []

  out = []
  for item in entries:
    if not isinstance(item, dict):
      continue
    out.append(C_isr_obj(
      id=str(item.get('id', '')),
      to=_normalize_alias_value(item.get('to')) or '',
      sig=_normalize_alias_value(item.get('sig'), 'id_symbol') or '',
    ))

  return out


def lukupmodel_outexec_logic(yaml_text):
  """Parse top-level OUTEXEC entries into C_outexec_obj models."""
  payload = yaml.safe_load(yaml_text) or {}
  entries = payload.get('outexec', [])
  if not isinstance(entries, list):
    return []

  out = []
  for item in entries:
    if not isinstance(item, dict):
      continue
    out.append(C_outexec_obj(
      name=str(item.get('name', '')),
      handler=str(item.get('handler', '')),
      context=_normalize_alias_value(item.get('context')),
      state=_normalize_alias_value(item.get('state')) or '',
    ))

  return out


def lukupmodel_glbda_logic(yaml_text):
  """Parse the top-level `glbda` section into C_gda_resrc_obj models."""
  payload = yaml.safe_load(yaml_text) or {}
  entries = payload.get('glbda', [])
  if not isinstance(entries, list):
    # Some YAML variants use a mapping keyed by numeric index instead of a list.
    entries = payload.get('glbda', {})
    if isinstance(entries, dict):
      items = []
      for index_key, item in entries.items():
        if isinstance(item, dict):
          item_with_index = dict(item)
          item_with_index['_index'] = str(index_key)
          items.append(item_with_index)
      entries = items
    else:
      return []

  anchors = _extract_anchor_list_for_group(yaml_text, 'glbda')
  out = []
  for idx, item in enumerate(entries, start=1):
    if not isinstance(item, dict):
      continue

    index_key = str(item.get('_index', idx))
    out.append(C_gda_resrc_obj(
      index=index_key,
      name=str(item.get('name', '')),
      kwtype=str(item.get('type', item.get('kwtype', ''))),
      initial_value=item.get('initial_value', ''),
      anchor=anchors[idx - 1] if idx - 1 < len(anchors) else '',
    ))

  return out


def lukupmodel_parse_sample(yaml_text):
  events = yaml.parse(yaml_text)
  pprint.pprint(list(events))
  print('--- End of Event Stream ---')

# STUB - Sample usage
if __name__ == '__main__':
  with open('sources/app/lstaxizer.yaml', 'r', encoding='utf-8') as f:
    yaml_sample = f.read()

  lukupmodel_parse_sample(yaml_sample)

  tnorm_items = lukupmodel_tnorm_resrc(yaml_sample)
  tpoll_items = lukupmodel_tpoll_resrc(yaml_sample)
  sig_items = lukupmodel_sig_resrc(yaml_sample)

  print('tnorm_count=', len(tnorm_items))
  for item in tnorm_items:
    print(item.index, item.id_symbol, item.handler, item.anchor)
    print('tsm =', item.tsm_resrc.kwobject if item.tsm_resrc else None)
    print('fsm =', item.fsm_resrc.kwobject if item.fsm_resrc else None)

  print('\n')

  print('tpoll_count=', len(tpoll_items))
  for item in tpoll_items:
    print(item.index, item.id_symbol, item.handler, item.anchor)

  print('\n')

  print('sig_count=', len(sig_items))
  for item in sig_items:
    print(item.index, item.id_symbol, item.hex_val, getattr(item, 'anchor', ''))

  print('\n')

  tnorm_logic_items = lukupmodel_tnorm_logic(yaml_sample)
  tpoll_logic_items = lukupmodel_tpoll_logic(yaml_sample)
  isr_logic_items = lukupmodel_isr_logic(yaml_sample)
  outexec_logic_items = lukupmodel_outexec_logic(yaml_sample)
  glbda_logic_items = lukupmodel_glbda_logic(yaml_sample)

  print('tnorm_logic_count=', len(tnorm_logic_items))
  print('\n')
  for item in tnorm_logic_items:
    print('task =', item.task)
    print('anchor =', item.anchor)
    if item.tsm:
      print('tsm_count =', len(item.tsm.tsm_list))
      for tsm in item.tsm.tsm_list:
        print('  state_id =', tsm.id)
        print('  trans =', [(t.sig, t.goto) for t in tsm.trans.trans])
        if tsm.on_ntry:
          print('  on_ntry =', [(a.actv, a.to, a.sig, a.data, a.ptype) for a in tsm.on_ntry.steps])
        if tsm.on_actv:
          print('  on_actv =', [(a.actv, a.to, a.sig, a.data, a.ptype) for a in tsm.on_actv.steps])
        if tsm.on_exit:
          print('  on_exit =', [(a.actv, a.to, a.sig, a.data, a.ptype) for a in tsm.on_exit.steps])
    if item.fsm:
      print('fsm_count =', len(item.fsm.fsm_list))
      for fsm in item.fsm.fsm_list:
        print('  fsm_id =', fsm.id)
        for recv in fsm.on_recv.on_recv:
          print('    recv_sig =', recv.sig, 'goto =', recv.goto)
          print('    recv_steps =', [(a.actv, a.to, a.sig, a.data, a.ptype) for a in recv.steps.steps])
    if item.kwexec:
      print('kwexec_count =', len(item.kwexec.kwexec))
      for kw in item.kwexec.kwexec:
        print('  kw_on_sig =', kw.on_sig)
        print('  kw_steps =', [(a.actv, a.to, a.sig, a.data, a.ptype) for a in kw.steps.steps])
    if item.escal:
      print('escal_mode =', item.escal.mode)
      print('escal_triggers =', [(t.on_sig, t.post_urgent.steps if t.post_urgent else None) for t in item.escal.trigger.trigger])
    print('\n')

  print('tpoll_logic_count=', len(tpoll_logic_items))
  for item in tpoll_logic_items:
    print('tpoll =', item.tpoll)
    print('kwexec_count =', len(item.kwexec))
    for act in item.kwexec:
      print('  action =', act.actv, act.to, act.sig, act.data, act.ptype)
    print('\n')

  print('isr_logic_count=', len(isr_logic_items))
  for item in isr_logic_items:
    print('isr_id =', item.id)
    print('isr_to =', item.to)
    print('isr_sig =', item.sig)
    print('\n')

  print('outexec_logic_count=', len(outexec_logic_items))
  for item in outexec_logic_items:
    print('name =', item.name)
    print('handler =', item.handler)
    print('context =', item.context)
    print('state =', item.state)
    print('\n')

  print('glbda_logic_count=', len(glbda_logic_items))
  for item in glbda_logic_items:
    print('gda_index =', item.index)
    print('gda_name =', item.name)
    print('gda_type =', item.kwtype)
    print('gda_initial_value =', item.initial_value)
    print('\n')


# TASK
'''
1. Thực hiện phân tích cấu trúc trả về của event để phân tích chiến lược xử lý mapping vào model.
2. Xây dựng các chuỗi phân tách phụ thuộc sẵn có từ lstaxer.strucjec để hỗ trợ triển khai.
'''

# DOC - Sample output for strategy of parsing into pydantic model

# NOTE - Extracting event stream

''' 
# SECTION - Idea for parsing into pydantic model
# LINK - pltf/testspec/lstaxer/lukupmodel_lstaxer.py:70

Follow from sample idea with parsing follow specific attribute,
we should add another mapping to specify which chain should be ignored
when mapping into pydantic model, because some attribute is not used in the model, 
but it is used in the YAML file to support semantic meaning.

For example, when moving between level tags like `tsm_resc` and `states`,
it is not necessary to check for any attribute between.
However, with the mapping between the specific attribute and the level tag,
it can be used to bypass the intermediate attribute and directly map to the next level tag.
# !SECTION
'''

'''
[StreamStartEvent(),
 DocumentStartEvent(),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tnorms'), # ANCHOR - must have section
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='1'),
 # NOTE - entry of tnorms must map to sequence structure tsm_resrc -> fsm_resrc -> id_symbol -> queue_name -> handler -> hex_val
 # NOTE - anchor is ahead of any attribute of the mapping, therefore, must be used to check the logic of the mapping
 MappingStartEvent(anchor='tnorm1-ctrl', tag=None, implicit=True),
 # NOTE - tsm_resc must map to sequence structure states -> state_trans -> object -> table
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tsm_resrc'),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='states'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tsm_task_usr_state_idle'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tsm_task_usr_state_running'),
 SequenceEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='state_trans'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tsm_task_usr_state_idle_trans'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tsm_task_usr_state_running_trans'),
 SequenceEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='object'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tsm_task_usr'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='table'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tsm_task_usr_tbl'),
 MappingEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='fsm_resrc'),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 # NOTE - fsm_resrc must map to sequence structure states -> object
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='states'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='FSM_TASK_1_STATE_1_ID'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='FSM_TASK_1_STATE_2_ID'),
 SequenceEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='object'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='FSM_TASK_1_ID'),
 MappingEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='id_symbol'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='TASK_NORM_USR'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='queue_name'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tnorm_usr_msgq'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='handler'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tnorm_usr_nhler'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='hex_val'),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='0xe3'),
 MappingEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='2'),
 MappingStartEvent(anchor='tnorm2-ctrl', tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tsm_resrc'),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='states'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tsm_task_a_state_idle'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tsm_task_a_state_waiting'),
 SequenceEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='state_trans'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tsm_task_a_state_idle_trans'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tsm_task_a_state_waiting_trans'),
 SequenceEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='object'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tsm_task_a'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='table'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tsm_task_a_tbl'),
 MappingEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='fsm_resrc'),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='states'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='FSM_TASK_2_STATE_1_ID'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='FSM_TASK_2_STATE_2_ID'),
 SequenceEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='object'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='FSM_TASK_2_ID'),
 MappingEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='id_symbol'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='TASK_NORM_A'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='queue_name'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tnorm_a_msgq'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='handler'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tnorm_a_nhler'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='hex_val'),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='0xe4'),
 MappingEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='3'),
 MappingStartEvent(anchor='tnorm3-ctrl', tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tsm_resrc'),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='states'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='TSM_TASK_3_STATE_1_ID'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='TSM_TASK_3_STATE_2_ID'),
 SequenceEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='state_trans'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='TSM_TASK_3_STATE_1_ID_trans'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='TSM_TASK_3_STATE_2_ID_trans'),
 SequenceEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='object'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='TSM_TASK_3_ID'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='table'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='TSM_TASK_3_ID_tbl'),
 MappingEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='fsm_resrc'),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='states'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='fsm_task_b_state_idle'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='fsm_task_b_state_busy'),
 SequenceEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='object'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='fsm_task_b'),
 MappingEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='id_symbol'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='TASK_NORM_B'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='queue_name'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tnorm_b_msgq'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='handler'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tnorm_b_nhler'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='hex_val'),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='0xe5'),
 MappingEndEvent(),
 MappingEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tpolls'), # ANCHOR - must have section
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='1'),
 MappingStartEvent(anchor='tpoll1-ctrl', tag=None, implicit=True),
 # NOTE - entry of tpolls must map to sequence structure id_symbol -> handler -> hex_val
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='id_symbol'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='TASK_POLL_MEMRP'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='handler'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tpoll_memrp'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='hex_val'),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='0xd0'),
 MappingEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='2'),
 MappingStartEvent(anchor='tpoll2-ctrl', tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='id_symbol'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='TASK_POLL_BLINK'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='handler'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tpoll_blink'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='hex_val'),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='0xd1'),
 MappingEndEvent(),
 MappingEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='sigs'),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='1'),
 MappingStartEvent(anchor='sig1', tag=None, implicit=True),
 # NOTE - entry of sigs must map to sequence structure id_symbol -> hex_val
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='id_symbol'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='SIG_USR_START'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='hex_val'),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='0x1'),
 MappingEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='2'),
 MappingStartEvent(anchor='sig2', tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='id_symbol'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='SIG_USR_STOP'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='hex_val'),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='0x2'),
 MappingEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='3'),
 MappingStartEvent(anchor='sig3', tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='id_symbol'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='SIG_0X34'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='hex_val'),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='0x3'),
 MappingEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='4'),
 MappingStartEvent(anchor='sig4', tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='id_symbol'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='SIG_0XFF'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='hex_val'),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='0x4'),
 MappingEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='5'),
 MappingStartEvent(anchor='sig5', tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='id_symbol'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='SIG_0X12'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='hex_val'),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='0x5'),
 MappingEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='6'),
 MappingStartEvent(anchor='sig6', tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='id_symbol'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='SIG_0XAA'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='hex_val'),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='0x6'),
 MappingEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='7'),
 MappingStartEvent(anchor='sig7', tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='id_symbol'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='SIG_HALT_NOW'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='hex_val'),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='0x7'),
 MappingEndEvent(),
 MappingEndEvent(),
 # NOTE - ignore
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='pject'),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='uEDP_PingPong_Full_Validation'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='versh'),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='1.2.0-pre'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='glbda'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='1'),
 ScalarEvent(anchor='gda_status', tag=None, implicit=(True, False), value=''),
 # NOTE - entry of glbda must map to sequence structure name -> type -> initial_value
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='name'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='GDA_SYSTEM_STATUS'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='type'),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='const char*'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='initial_value'),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='STATUS: INITIALIZING'),
 MappingEndEvent(),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='2'),
 ScalarEvent(anchor='gda_counter', tag=None, implicit=(True, False), value=''),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='name'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='GDA_COUNTER'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='type'),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='int'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='initial_value'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='0'),
 MappingEndEvent(),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='3'),
 ScalarEvent(anchor='gda_flag', tag=None, implicit=(True, False), value=''),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='name'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='GDA_FLAG'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='type'),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='bool'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='initial_value'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='false'),
 MappingEndEvent(),
 SequenceEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tlist'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tnorm'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='TASK_NORM_USR'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tsm'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 # NOTE - entry of tsm-item must map to sequence structure id -> trans -> on-ntry -> on-actv -> on-exit
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='id'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tsm_task_usr_state_idle'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='trans'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 # NOTE - entry of trans must map to single trans-obj or list of trans-obj
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 # NOTE - entry of trans-obj must map to sequence structure sig -> goto
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='sig'),
 AliasEvent(anchor='sig1'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='goto'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tsm_task_usr_state_running'),
 MappingEndEvent(),
 SequenceEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='on_ntry'),
 # NOTE - on-ntry must map to single actv-obj or list of actv-obj = steps
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='steps'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 # NOTE - entry of steps is a list of actv-obj
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 # NOTE - entry of steps or single actv-obj must map to sequence structure actv -> to -> sig -> data -> ptype
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='actv'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='uedp_itnlog_init()'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='to'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='sig'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='data'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='ptype'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 MappingEndEvent(),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='actv'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='uedp_itnlog_set_output(pal_logdp_dispatch)'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='to'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='sig'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='data'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='ptype'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 MappingEndEvent(),
 SequenceEndEvent(),
 MappingEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='on_actv'),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='steps'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='actv'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='uedp_itnlog_log'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='to'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='sig'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='data'),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='[USR][IDLE] Starting sequence...'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='ptype'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 MappingEndEvent(),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='actv'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='uedp_task_norm_post_msg'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='to'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='TASK_NORM_A'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='sig'),
 AliasEvent(anchor='sig1'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='data'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='ptype'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 MappingEndEvent(),
 SequenceEndEvent(),
 MappingEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='on_exit'),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='actv'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='uedp_itnlog_log'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='to'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='sig'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='data'),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='[USR][IDLE] Sequence finished.'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='ptype'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 MappingEndEvent(),
 MappingEndEvent(),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='id'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tsm_task_usr_state_running'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='trans'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='sig'),
 AliasEvent(anchor='sig2'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='goto'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tsm_task_usr_state_idle'),
 MappingEndEvent(),
 SequenceEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='on_ntry'),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='actv'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='uedp_itnlog_log'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='to'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='sig'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='data'),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='[USR][RUNNING] Sequence started.'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='ptype'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 MappingEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='on_actv'),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='steps'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='actv'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='uedp_itnlog_log'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='to'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='sig'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='data'),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='[USR][RUNNING] Posting message to TASK_NORM_A...'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='ptype'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 MappingEndEvent(),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='actv'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='uedp_task_norm_post_msg'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='to'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='TASK_NORM_A'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='sig'),
 AliasEvent(anchor='sig1'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='data'),
 AliasEvent(anchor='gda_status'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='ptype'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='REF'),
 MappingEndEvent(),
 SequenceEndEvent(),
 MappingEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='on_exit'),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='steps'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='actv'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='ocesvc_register'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='to'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='sig'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='data'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='itnlog_dump_svc'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='ptype'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 MappingEndEvent(),
 SequenceEndEvent(),
 MappingEndEvent(),
 MappingEndEvent(),
 SequenceEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='<<'),
 AliasEvent(anchor='tnorm1-ctrl'),
 MappingEndEvent(),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tnorm'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='TASK_NORM_A'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tsm'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='id'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tsm_task_a_state_idle'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='trans'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='sig'),
 AliasEvent(anchor='sig1'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='goto'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tsm_task_a_state_waiting'),
 MappingEndEvent(),
 SequenceEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='on_ntry'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='on_actv'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='on_exit'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 MappingEndEvent(),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='id'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tsm_task_a_state_waiting'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='trans'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='sig'),
 AliasEvent(anchor='sig3'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='goto'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='STAY'),
 MappingEndEvent(),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='sig'),
 AliasEvent(anchor='sig4'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='goto'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tsm_task_a_state_idle'),
 MappingEndEvent(),
 SequenceEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='on_ntry'),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='actv'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='uedp_post_msg'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='to'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='TASK_NORM_B'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='sig'),
 AliasEvent(anchor='sig5'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='data'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='ptype'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 MappingEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='on_actv'),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='steps'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='actv'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='uedp_post_msg'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='to'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='TASK_NORM_B'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='sig'),
 AliasEvent(anchor='sig6'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='data'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='ptype'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 MappingEndEvent(),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='actv'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='uedp_itnlog_log'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='to'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='sig'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='data'),
 ScalarEvent(anchor=None, tag=None, implicit=(False, True), value='[TASK_NORM_A][WAITING_B] Posted SIG_0xAA to TASK_NORM_B.'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='ptype'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 MappingEndEvent(),
 SequenceEndEvent(),
 MappingEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='on_exit'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 MappingEndEvent(),
 SequenceEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='escal'),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='mode'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='slnf'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='trigger'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='on_sig'),
 AliasEvent(anchor='sig7'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='post_urgent'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 MappingEndEvent(),
 SequenceEndEvent(),
 MappingEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='<<'),
 AliasEvent(anchor='tnorm2-ctrl'),
 MappingEndEvent(),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tnorm'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='TASK_NORM_B'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='fsm'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='id'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='fsm_task_b_state_idle'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='on_recv'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='sig'),
 AliasEvent(anchor='sig5'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='goto'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='fsm_task_b_state_busy'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='steps'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='actv'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='uedp_task_norm_post_msg'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='to'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='TASK_NORM_A'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='sig'),
 AliasEvent(anchor='sig3'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='data'),
 AliasEvent(anchor='gda_status'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='ptype'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='VAL'),
 MappingEndEvent(),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='actv'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='uedp_task_norm_post_msg'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='to'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='TASK_NORM_A'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='sig'),
 AliasEvent(anchor='sig4'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='data'),
 AliasEvent(anchor='gda_status'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='ptype'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='VAL'),
 MappingEndEvent(),
 SequenceEndEvent(),
 MappingEndEvent(),
 SequenceEndEvent(),
 MappingEndEvent(),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='id'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='fsm_task_b_state_busy'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='on_recv'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='sig'),
 AliasEvent(anchor='sig6'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='goto'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='fsm_task_b_state_idle'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='steps'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='actv'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='uedp_task_norm_post_msg'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='to'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='TASK_USR'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='sig'),
 AliasEvent(anchor='sig2'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='data'),
 AliasEvent(anchor='gda_status'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='ptype'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='REF'),
 MappingEndEvent(),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='actv'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='uedp_itnlog_log'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='to'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='sig'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='data'),
 AliasEvent(anchor='gda_status'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='ptype'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='VAL'),
 MappingEndEvent(),
 SequenceEndEvent(),
 MappingEndEvent(),
 SequenceEndEvent(),
 MappingEndEvent(),
 SequenceEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='<<'),
 AliasEvent(anchor='tnorm3-ctrl'),
 MappingEndEvent(),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tpoll'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='TASK_POLL_MEMRP'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='exec'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='actv'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='pal_memrp_report()'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='to'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='sig'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='data'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='ptype'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 MappingEndEvent(),
 SequenceEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='<<'),
 AliasEvent(anchor='tpoll1-ctrl'),
 MappingEndEvent(),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='tpoll'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='TASK_POLL_BLINK'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='exec'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='actv'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='pal_blink_led()'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='to'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='sig'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='data'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='ptype'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 MappingEndEvent(),
 SequenceEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='<<'),
 AliasEvent(anchor='tpoll2-ctrl'),
 MappingEndEvent(),
 SequenceEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='isr'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='id'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='ISR_HARD_STOP'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='to'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='TASK_NORM_A'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='sig'),
 AliasEvent(anchor='sig7'),
 MappingEndEvent(),
 SequenceEndEvent(),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='outexec'),
 SequenceStartEvent(anchor=None, tag=None, implicit=True),
 MappingStartEvent(anchor=None, tag=None, implicit=True),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='name'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='OCE_ITNLOG_DUMP'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='handler'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='itnlog_dump_handler'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='context'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='NULL'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='state'),
 ScalarEvent(anchor=None, tag=None, implicit=(True, False), value='READY'),
 MappingEndEvent(),
 SequenceEndEvent(),
 MappingEndEvent(),
 DocumentEndEvent(),
 StreamEndEvent()]
'''